### ISSUE TITLE
use https://github.com/jonathanong/s3-proxy-stream

### ISSUE THREAD

**Issue by jonathanong** [koajs/s3-cache#5]
would resolve #2 and #4

**Comment by chrisveness** [comment]
Not sure I follow – don't range requests (#2) have a wider application than S3? (admittedly, my only use-case has been S3).

**Comment by jonathanong** [comment]
the library i just made supports range requests, so if you pass `req.headers.range` the result will be returned with the correct range - s3 handles the logic

**Comment by chrisveness** [comment]
Sounds good.
